Repository classmethod/gradle-aws-plugin, pull requests merged in 2018-03, with the labels that each got.

#138 Depend on Lombok only for compiling
  build.gradle
Labels: refactoring

#130 Allow json comments in beanstalk configuration templates
  src/main/java/jp/classmethod/aws/gradle/elasticbeanstalk/AWSElasticBeanstalkCreateConfigurationTemplateTask.java
Labels: enhancement

#135 Add RDS cluster tasks, and bump aws dependency version to 1.11.267
  build.gradle
  src/main/java/jp/classmethod/aws/gradle/rds/AmazonRDSCreateDBInstanceTask.java
  src/main/java/jp/classmethod/aws/gradle/rds/AmazonRDSDeleteDBClusterTask.java
  src/main/java/jp/classmethod/aws/gradle/rds/AmazonRDSDescribeInstanceTask.java
  src/main/java/jp/classmethod/aws/gradle/rds/AmazonRDSDescribeInstancesTask.java
  src/main/java/jp/classmethod/aws/gradle/rds/AmazonRDSRestoreDbClusterToPointInTimeTask.java
  src/main/java/jp/classmethod/aws/gradle/rds/AmazonRDSWaitClusterStatusTask.java
Labels: enhancement

#141 Lambda versioning
  README.md
  src/main/java/jp/classmethod/aws/gradle/lambda/AWSLambdaMigrateFunctionTask.java
Labels: enhancement

#142 update spotless
  build.gradle
Labels: chore
